/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Dinopc
 */
public class Agendamento extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agendamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Button = new java.awt.Button();
        SelectTipo = new javax.swing.JComboBox<>();
        SelectCliente = new javax.swing.JComboBox<>();
        InputData = new javax.swing.JFormattedTextField();
        TxtObservacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputObservacao = new javax.swing.JTextArea();
        TxtHorario = new javax.swing.JLabel();
        InputHorario = new javax.swing.JTextField();
        TxtData = new javax.swing.JLabel();
        InputValor = new javax.swing.JTextField();
        TxtValor = new javax.swing.JLabel();
        TxtTipo = new javax.swing.JLabel();
        TxtCliente = new javax.swing.JLabel();
        TxtNome = new javax.swing.JLabel();
        InputNome = new javax.swing.JTextField();
        FundoSecundario = new javax.swing.JLabel();
        FundoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Cliente", "Valor", "Data", "Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 1040, 230));

        Button.setBackground(new java.awt.Color(51, 154, 139));
        Button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setLabel("Agendar Locação");
        getContentPane().add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 1040, 40));

        SelectTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(SelectTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 390, 30));

        SelectCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(SelectCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 390, 30));

        InputData.setToolTipText("");
        getContentPane().add(InputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 390, 30));

        TxtObservacao.setBackground(new java.awt.Color(255, 255, 255));
        TxtObservacao.setForeground(new java.awt.Color(255, 255, 255));
        TxtObservacao.setText("Observações:");
        getContentPane().add(TxtObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, -1));

        InputObservacao.setColumns(20);
        InputObservacao.setRows(5);
        jScrollPane1.setViewportView(InputObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 400, 110));

        TxtHorario.setBackground(new java.awt.Color(255, 255, 255));
        TxtHorario.setForeground(new java.awt.Color(255, 255, 255));
        TxtHorario.setText("Horário:");
        getContentPane().add(TxtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));
        getContentPane().add(InputHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 390, 30));

        TxtData.setBackground(new java.awt.Color(255, 255, 255));
        TxtData.setForeground(new java.awt.Color(255, 255, 255));
        TxtData.setText("Data:");
        getContentPane().add(TxtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));
        getContentPane().add(InputValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 390, 30));

        TxtValor.setBackground(new java.awt.Color(255, 255, 255));
        TxtValor.setForeground(new java.awt.Color(255, 255, 255));
        TxtValor.setText("Valor (R$):");
        getContentPane().add(TxtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        TxtTipo.setBackground(new java.awt.Color(255, 255, 255));
        TxtTipo.setForeground(new java.awt.Color(255, 255, 255));
        TxtTipo.setText("Tipo quadra:");
        getContentPane().add(TxtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        TxtCliente.setBackground(new java.awt.Color(255, 255, 255));
        TxtCliente.setForeground(new java.awt.Color(255, 255, 255));
        TxtCliente.setText("Cliente:");
        getContentPane().add(TxtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        TxtNome.setBackground(new java.awt.Color(255, 255, 255));
        TxtNome.setForeground(new java.awt.Color(255, 255, 255));
        TxtNome.setText("Nome:");
        getContentPane().add(TxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));
        getContentPane().add(InputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 390, 30));

        FundoSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagem/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(FundoSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, -1, -1));

        FundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagem/AgendaFundo.jpg"))); // NOI18N
        getContentPane().add(FundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Button;
    private javax.swing.JLabel FundoPrincipal;
    private javax.swing.JLabel FundoSecundario;
    private javax.swing.JFormattedTextField InputData;
    private javax.swing.JTextField InputHorario;
    private javax.swing.JTextField InputNome;
    private javax.swing.JTextArea InputObservacao;
    private javax.swing.JTextField InputValor;
    private javax.swing.JComboBox<String> SelectCliente;
    private javax.swing.JComboBox<String> SelectTipo;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel TxtCliente;
    private javax.swing.JLabel TxtData;
    private javax.swing.JLabel TxtHorario;
    private javax.swing.JLabel TxtNome;
    private javax.swing.JLabel TxtObservacao;
    private javax.swing.JLabel TxtTipo;
    private javax.swing.JLabel TxtValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
