/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Dinopc
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Linha = new javax.swing.JSeparator();
        InputSenha = new javax.swing.JPasswordField();
        InputUsuario = new javax.swing.JTextField();
        TxtSenha = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JLabel();
        TxtLogin = new javax.swing.JLabel();
        FundoSecundario = new javax.swing.JLabel();
        FundoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Linha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 392, 450, 10));
        getContentPane().add(InputSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 430, 30));
        getContentPane().add(InputUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 440, 30));

        TxtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtSenha.setForeground(new java.awt.Color(255, 255, 255));
        TxtSenha.setText("Senha:");
        getContentPane().add(TxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        TxtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TxtUsuario.setText("Usuário :");
        getContentPane().add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        TxtLogin.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        TxtLogin.setForeground(new java.awt.Color(255, 255, 255));
        TxtLogin.setText("Login");
        getContentPane().add(TxtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        FundoSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagem/painel-login.png"))); // NOI18N
        getContentPane().add(FundoSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        FundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagem/Logo.jpg"))); // NOI18N
        getContentPane().add(FundoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoPrincipal;
    private javax.swing.JLabel FundoSecundario;
    private javax.swing.JPasswordField InputSenha;
    private javax.swing.JTextField InputUsuario;
    private javax.swing.JSeparator Linha;
    private javax.swing.JLabel TxtLogin;
    private javax.swing.JLabel TxtSenha;
    private javax.swing.JLabel TxtUsuario;
    // End of variables declaration//GEN-END:variables
}
