/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import Controller.ClienteController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Dinopc
 */
public class ViewCliente extends javax.swing.JFrame {

    private final ClienteController controller;

    /**
     * Creates new form Agenda
     */
    public ViewCliente() {
        initComponents();
        controller = new ClienteController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputRg = new javax.swing.JTextField();
        TxtRg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        TxtEmail = new javax.swing.JLabel();
        InputEmail = new javax.swing.JTextField();
        Button = new java.awt.Button();
        InputData = new javax.swing.JFormattedTextField();
        TxtData = new javax.swing.JLabel();
        TxtNome = new javax.swing.JLabel();
        InputNome = new javax.swing.JTextField();
        FundoSecundario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(InputRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 390, 30));

        TxtRg.setBackground(new java.awt.Color(255, 255, 255));
        TxtRg.setForeground(new java.awt.Color(255, 255, 255));
        TxtRg.setText("RG:");
        getContentPane().add(TxtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data", "E-mail", "RG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabela);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 1040, 230));

        TxtEmail.setBackground(new java.awt.Color(255, 255, 255));
        TxtEmail.setForeground(new java.awt.Color(255, 255, 255));
        TxtEmail.setText("E-mail:");
        getContentPane().add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(InputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 390, 30));

        Button.setActionCommand("Criar Cliente");
        Button.setBackground(new java.awt.Color(51, 154, 139));
        Button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Button.setForeground(new java.awt.Color(255, 255, 255));
        Button.setLabel("Criar Cliente");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 1040, 40));

        InputData.setToolTipText("");
        getContentPane().add(InputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 390, 30));

        TxtData.setBackground(new java.awt.Color(255, 255, 255));
        TxtData.setForeground(new java.awt.Color(255, 255, 255));
        TxtData.setText("Data Nascimento:");
        getContentPane().add(TxtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        TxtNome.setBackground(new java.awt.Color(255, 255, 255));
        TxtNome.setForeground(new java.awt.Color(255, 255, 255));
        TxtNome.setText("Nome:");
        getContentPane().add(TxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(InputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 390, 30));

        FundoSecundario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagem/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(FundoSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1170, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        this.controller.agendar();
    }//GEN-LAST:event_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Button;
    private javax.swing.JLabel FundoSecundario;
    private javax.swing.JFormattedTextField InputData;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputNome;
    private javax.swing.JTextField InputRg;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel TxtData;
    private javax.swing.JLabel TxtEmail;
    private javax.swing.JLabel TxtNome;
    private javax.swing.JLabel TxtRg;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizarTabela();
    }

    public JTable getTabela() {
        return Tabela;
    }

    public void setTabela(JTable Tabela) {
        this.Tabela = Tabela;
    }

    public JFormattedTextField getInputData() {
        return InputData;
    }

    public void setInputData(JFormattedTextField InputData) {
        this.InputData = InputData;
    }
    

    public JTextField getInputNome() {
        return InputNome;
    }

    public void setInputNome(JTextField InputNome) {
        this.InputNome = InputNome;
    }

    public JTextField getInputEmail() {
        return InputEmail;
    }

    public void setInputEmail(JTextField InputEmail) {
        this.InputEmail = InputEmail;
    }

    public JTextField getInputRg() {
        return InputRg;
    }

    public void setInputRg(JTextField InputRg) {
        this.InputRg = InputRg;
    }
    
}
